### ISSUE TITLE
[Bug(?)] Maximize and Fullscreen Problem

### ISSUE THREAD

**Issue by ditokp** [ktabata/suika2#10]
Hello, I found this when playing the demo game.

I can't maximize the game window. The game window doesn't have maximize icon. Screenshot:
![2018-12-24-151440_1282x749_scrot](https://user-images.githubusercontent.com/27815899/50394608-43c2c100-0791-11e9-9ea7-423baaf53d73.png)

And when I press F11 to go to fullscreen mode. The game not going fullscreen. Screenshot:
![2018-12-24-151615_1366x768_scrot](https://user-images.githubusercontent.com/27815899/50394667-9603e200-0791-11e9-998f-276724c49503.png)

I have read this issue #2, but not found any solution. I think that issue being closed because the bug is fixed, but I'm wrong.

My system specs:
OS: Lubuntu 18.04.1 LTS 64-bit
Screen Resolution: 1366x768

**Comment by ktabata** [comment]
> I can't maximize the game window. The game window doesn't have maximize icon. Screenshot:

Sorry, window maximization is not implemented on X11.

> And when I press F11 to go to fullscreen mode. The game not going fullscreen. Screenshot:

Sorry, full screen mode is not implemented on X11.
On GNOME3, when pressing F11, nothing happens.
I'll try it on LXDE.

**Comment by ditokp** [comment]
Okay, thank you for replying my issue
