### ISSUE TITLE
How to Make the Choosing game menu with keyboard?

### ISSUE THREAD

**Issue by ditokp** [ktabata/suika2#11]
Hello, I have little problem. For now, I only can choosing game menu with mouse. Screenshot:

![2018-12-24-152147_1280x720_scrot](https://user-images.githubusercontent.com/27815899/50394870-04956f80-0793-11e9-913d-86f6f720dbb8.png)

How to use keyboard for choosing game menu? In other game engine, for example Renpy, I can choose both with mouse and keyboard.

**Comment by ktabata** [comment]
Currently, the only function which supports up/down key is the log screen.
I can expand the scope of the keyboard operations by small changes.
Do you need the keyboard operations?
