### ISSUE TITLE
[Question] Can I Insert Video to the Visual Novel?

### ISSUE THREAD

**Issue by ditokp** [ktabata/suika2#15]
I have read tutorial.md and command reference.md file, but I'm not found the command. So I only want to ask a question, and not requesting the ability to add video.

so, can I insert video to the suika 2?

**Comment by ktabata** [comment]
Video playback is currently not supported. I want to support it someday.
I've once tried Ogg/Theora, but I haven't understand how to decode Theora.

**Comment by ditokp** [comment]
Thank you very much for answering my question. I will wait until this feature added. Have a nice day :-)

**Comment by 2439905184** [comment]
bkeingine use ffmpeg.dll to decode mp4 file.Another visual novel engine based on cocos2dx (but not open source)

**Comment by ktabata** [comment]
I have concluded that Windows-only support for video playback is relatively easy and cross platform implementation is relatively difficult.

**Comment by 2439905184** [comment]
> 我得出的结论是，仅Windows对视频播放的支持相对容易，跨平台实现相对困难。
godot engine can decode webm video.I think it is cross platform.May be you can get some ways to decode video file with godot engine's source code with webm module.

**Comment by 2439905184** [comment]
But I think there is another way to implement play video.
Just use
```
@bgm file.ogg
```
to play bgm
and then use 
```
@bg file.png
```
 to change bg fast.
So,my way is to play bgm and image frames in different files ,not in one encoded video file.（60fps）
I haven't try this method.
```
@bgm bgm.ogg
@bg 1.png
@wait 0.016
@bg 2.png
@wait 0.016
@bg 3.png
@wait 0.016
```
this script will be very long,so it is need to generate by another program such as python program.

**Comment by 2439905184** [comment]
@ktabata is this a good way?

**Comment by ktabata** [comment]
@2439905184 Haha. Usually "anime" is produced with 24fps. Decoding 24 HD PNG images in a second is heavy workload, I think. So this is not a good way. But I'd like to respect your challenging approach.
I want to use video decoding acceleration on Windows. I guess using DirectShow and WMV9 may be easiest way.
