### ISSUE TITLE
[Improvement] Enhancement idea for sprite display.

### ISSUE THREAD

**Issue by lochana-Dineko** [ktabata/suika2#16]
I've been testing this for some time, and I've noticed that Suika when it displays character sprite images it displays them from left to right meaning that if I have a character sprite .png with that has a horizontal length of 256 the engine displays the image on starting with the 1st pixel. This causes an issue with positioning characters.

In Nscripter and Kirikiri 2 when you display an image file it is displayed by dividing the horizontal length of the sprite and displaying it from the middle. This is would be an improvement for bigger sprites. Just a suggestion. Images attached

For example with this image file I'm defining the character to stand in left but the character is show in the middle due to the hoirzontal length.

![tie_1_2](https://user-images.githubusercontent.com/30839724/65332198-d5a21200-dbdb-11e9-9dcf-3bc4600b4739.png)
![Capture](https://user-images.githubusercontent.com/30839724/65332246-eb173c00-dbdb-11e9-95da-52e1a891ae9e.PNG)

Thank you.

**Comment by ktabata** [comment]
@lochana-Dineko Thank you for your advice.
I would be happy if you could provide me some example scripts for Nscripter or Kirikiri2 because I've never used them.

**Comment by ktabata** [comment]
By the way, why do you want such a large character image?

**Comment by lochana-Dineko** [comment]
Sorry for taking a while to respond.

The image file is like that because that is how it was converted from the PSvita, As for scripts I will attach them here. Although the image position handling is done by the engine itself.

Basic Nscripter script files;
[99.txt](https://github.com/ktabata/suika2/files/3638185/99.txt)
[0.txt](https://github.com/ktabata/suika2/files/3638186/0.txt)
[1.txt](https://github.com/ktabata/suika2/files/3638188/1.txt)
