### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Dungeonmir** [ktabata/suika2#17]
How to build android apk?
I installed android studio but it has a lot of errors, when i use build/android/build.grandle.

**Comment by ktabata** [comment]
Thank you for your interest in this project.
Last time I checked, Android Studio was 3.3.1, so try 3.3.1 from Android Studio Archive.
Below was the list of steps I checked.

- Install Android Studio 3.3.1
- Start Android Studio.
- Select "Configure" on initial screen.
- Select "CMake", "LLDB", "NDK".
- Run installation of CMake, LLDB, NDK.
- Open Suika2 project.
- Android Studio says "Failed to find Build Tools revision 27.0.3".
- Push "Install Build Tools 27.0.3 and sync project"

Hope this helps.
