### ISSUE TITLE
[Suggestion] Text Shadow and Text Outline.

### ISSUE THREAD

**Issue by lochana-Dineko** [ktabata/suika2#18]
I'm happy that development is going on. Thank you for your hard work. Even though I'm in Exam year I'm still working on my project little my little.

This isn't a big problem but will improve readability for text.
Normally Visual Novels have text shadows that makes text look a little bit better.
![Wikipe-tan_visual_novel](https://user-images.githubusercontent.com/30839724/109412862-6c2d5200-79d0-11eb-9076-28266c1b598b.png)

This is the first example I could find. This is a little too much but the generally there is a black text shadows that is 2 or 1 pixel to the right of the text.

Text outline is something similar. There is a 1 px outline around around the text which makes things more readable. 

It's a general suggestion. Thank you for your hard work.

If possible a NVL mode would also probably be a good idea. More detailed visual novels like F/SNight, Higurashi/Umineko/Ciconia no naku koro ni all all use NVL mode.

![higurashi_vita](https://user-images.githubusercontent.com/30839724/109414606-c1ba2c80-79d9-11eb-9d8f-eb7a1d96c925.png)

It could be a setting that you change in the config file. Which would allow you change several things.
Example - NVL.mode=true

Normally when you write.

Hello I'm Neoko. Pleased to meet you!
The sky is blue isn't it?

The text will clear after the first line. Instead we could make it so that text will not clear and instead continue on the next line after a linebreak.

And a command like *clearscreen to clear the text and begin from the top text again.

It's a suggestion. Please fell free to close this issue if you want to. Thanks.

**Comment by ktabata** [comment]
Thank you for your feedback and suggestion!

I'm 100 percent sure that text readability is very important to all users of Suika2.

Generally, soft shadow like your example may cause high CPU usage.
I would say 1px shadow or outline is reasonable for both speed and simplicity of implementation.
Does it meet your needs?

Also, NVL mode is a big job, but I realized your needs.
I would be happy if we could discuss its functionality and feasibility in other issue.

**Comment by lochana-Dineko** [comment]
Thanks for responding. Then I will close this issue and open another to discuss the feasibility of a nvl mode.
