### ISSUE TITLE
[Suggestion] Feasibility of a NVL.

### ISSUE THREAD

**Issue by lochana-Dineko** [ktabata/suika2#19]
Based on the post from suggestion,

From my experience, a nvl mode is not a 100% requirement. Instead it seems to be brought out from design. I have some experience working with Visual Novels so for Understanding feasibility we would probably need to see how the other do it.

### Nscripter - Onscripter - Ponscripter,

Nscripter and it's derivative implementations use a mix of nvl and adv mode. For example in my script.

`^Wahahaha! You have no choice but to give up Ushiromiya Battler!^@`

`^` is used to contain text as Nscripter was not made with English support. Here `@` is used as to get a click from the user.

`^Wahahaha! You have no choice but to give up Ushiromiya Battler!^`
`^You're pure evil Beato. Pure evil^@`

`^` is absent in the first line. Nscripter goes through the text without waiting for a click and moves to the next line. The user would only need to click once

`^"Wahahaha! You have no choice but to give up Ushiromiya Battler!"^@`
`^"You're pure evil Beato. Pure evil."^@`

Here the user will have to click twice. Once after "Battler" and once after "evil"

I'll post a screenshot.
![Capture](https://user-images.githubusercontent.com/30839724/109418725-e6210380-79ef-11eb-943d-714b55cb9ceb.PNG)
![Capture2](https://user-images.githubusercontent.com/30839724/109418714-df928c00-79ef-11eb-97c1-ef9ac299ff82.PNG)

After that Imagine we want to clear all text and move to a new page.

`^"Wahahaha! You have no choice but to give up Ushiromiya Battler!"^@`
`^"You're pure evil Beato. Pure evil."^\`
`^"How can you explain this Battler? This is magic!"^`

Here there is a `\` which is the signal to the engine to clear the text and move to a new page.

![Capture3](https://user-images.githubusercontent.com/30839724/109419015-3b114980-79f1-11eb-8083-396a431fb82a.PNG)

**Comment by lochana-Dineko** [comment]
Since Suika uses a single line text processing script then this might not prove feasible for the effort.

However the ability to continue text to the next line without waiting for user confirmation does add some advantages.
Based on the post from suggestion,

`^"Wahahaha! You have no choice but to give up Ushiromiya Battler!"^`


`^"You're pure evil Beato. Pure evil."^\`

Here there is no `@` in the first line. There will be no click and it will directly continue to the next line. This could be useful for more effects.

`^"Wahahaha! You have no choice but to give up Ushiromiya Battler!"^`

ld l, "battler_tense.png"

`^"You're pure evil Beato. Pure evil."^\`
`^"How can you explain this Battler? This is magic!"^`

For example it can be used to change sprite in mid sentence.

**Comment by ktabata** [comment]
Thank you for your suggestion.
Could you please give me some time to think it over?

Suika2 uses single line script because each line is save point.
It is convenient for users to save at wait-for-click inside a long message, but its implementation may be incompatible and/or complicated.
It's not impossible, however, we should firstly design such save feature well.

**Comment by lochana-Dineko** [comment]
Of course. It's Just a suggestion.

A NVL mode is not all important. Suika 2 is great as it is. There are probably better things to be focused on in regards to the engine rather than NVL. NVL is probably a thing that should be focused on at last instead of a feature development point.

It's nice that Suika 2 automatically parses labels and turns each line into a save file. KiriKiri with KAG struggles to do so without the support of an external code which is a roundabout solution by itself.

Thanks for your feedback.
