### ISSUE TITLE
Small issue.

### ISSUE THREAD

**Issue by lochana-Dineko** [ktabata/suika2#2]
I noticed that when you go to full-screen mode the edges of screen are empty. Is there any way to fix that?

**Comment by ktabata** [comment]
I can change the behaviour of the full-screen mode.  Currently, Suika2 doesn't change the display size mode.  If you want to change the display size mode, please let me know.

**Comment by lochana-Dineko** [comment]
The fullscreen mode is not a big problem in monitors with small resoloution, however in bigger resouloutions it will be annoying. It'll be a improvemen
