### ISSUE TITLE
Indexed PNG not read properly

### ISSUE THREAD

**Issue by minirop** [ktabata/suika2#20]
Hello
I've implemented layered sprites and when testing with [this asset](https://duokhay.itch.io/brown-haired-girl-free-character-sprite-asset) I noticed the blush and the open mouths were blue instead of pink.
![blue_mouth](https://user-images.githubusercontent.com/451828/114286665-1fbe4300-9a61-11eb-9e0c-958e2a4dbecd.png)
When opening the files in GIMP, I saw that the wrongly displayed images had indexed colours.

Then I tried with the image alone `@ch c GPG_mouth_ah.png` and got the same result.
![image](https://user-images.githubusercontent.com/451828/114286743-c571b200-9a61-11eb-947a-5e0d28236c12.png)

**Comment by ktabata** [comment]
Hi, thank you for the report.
On Windows, I had to convert pixels RGB to BGR.
I've already fixed it and release it later.

**Comment by ktabata** [comment]
I've just released v2.7.1. Could you try it?

**Comment by minirop** [comment]
works. thanks.

**Comment by ktabata** [comment]
Thank you, minirop!
