### ISSUE TITLE
Suggestion : Emscripten support.

### ISSUE THREAD

**Issue by ishani-rgb** [ktabata/suika2#21]
Hello. Suika 2 supports almost every current platform. Are there plans to support Emscripten to run Suika2 games on the web? How feasible would it be?

**Comment by ktabata** [comment]
Hi ishani-rgb,

Well, I don't have a plan to support Emscripten for now because TyranoScript/TyranoBuilder are available for Web platform.
It is necessary to write a hardware abstraction layer (HAL) to port Suika2 to Emscripten. HAL must have following abilities.

* Image drawing
* Sound output
* File access
* Yes/No dialog

I have time today so I'm confirming image drawing. If you have time, could you help me check sound output?

Thanks.

**Comment by ishani-rgb** [comment]
Sure. I'm available. Lets check it out.

**Comment by ktabata** [comment]
Thank you. Following functions are defined for HAL:

* bool play_sound(int n, struct wave *w)
* bool stop_sound(int n)
* bool set_sound_volume(int n, float vol)

`int n` specifies the index of sound stream (BGM, voice, SE).
`struct wave *w` points to the sound file name or its content.

Can we implement these functions on Emscripten?
Please teach me if you know that.

**Comment by ishani-rgb** [comment]
I have used this one.
https://github.com/madureira/SDL_AudioPlayer
And it worked.

This might be whats needed? I know its compaitble with Emscripten.

**Comment by ktabata** [comment]
Thank you for your report.
Well, it seems html tag "audio" works without library.
I think the tag is enough to implement HAL.

**Comment by ktabata** [comment]
Showing pixel buffer is ok.  https://luxion.jp/em/html/
I haven't solved these items.

* File I/O
* Read PNG image and get pixels

**Comment by ishani-rgb** [comment]
As far as PNGs are concerned. This seems to work.
https://www.learnopengles.com/loading-a-png-into-memory-and-displaying-it-as-a-texture-with-opengl-es-2-using-almost-the-same-code-on-ios-android-and-emscripten/

File I/O should work as usual. Shouldnt it?

**Comment by ktabata** [comment]
The article you mentioned seems to compile whole libpng by Emscripten. If the approach has no trouble with speed, it is the easiest way to port, I think.

Can I use `fopen()` for the files which are accessed by HTTP? For example, let's say the application is deployed at https://luxion.jp/em/, can I read-access the files under em/? I searched the Internet but I'm not sure.

**Comment by ishani-rgb** [comment]
As for file system acccess. It should work.

https://emscripten.org/docs/getting_started/Tutorial.html

Sorry for the late responses btw.

**Comment by ktabata** [comment]
Thanks. I realized that files opened by `fopen()` must be preloaded when html is loaded. We must make a list of files and pass it to Emscripten when compile.
I wonder how Tyranoscript implements on-demand loading of files. Does it preload files too?

**Comment by ktabata** [comment]
Ok, it started working. After implementing mouse events, the sample game will run on browsers without sound.
https://luxion.jp/em/html/

**Comment by ishani-rgb** [comment]
I tested it. Wow. Congrats. Im not sure about audio support specifics but Im happy to see that it works.
Even functions like Save and Load work well.

This is amazing. Thanks for your work! Perhaps Emscripten build inscructions should also be added?

**Comment by ktabata** [comment]
Thanks for testing. It was relatively easy to port because Emscripten has prebuilt binaries for the libraries Suika2 depends on.

I found Emscripten supports audio playback by OpenAL 1.1 API. I'm currently working on it. After implementing sound, I'll write a build instructions manual.

BTW, if you feel Suika2 is lightweight, I'm not sure, but the image processing part of Suika2 might be vectorized for SSE/AVX instructions by JavaScript/WebAssembly engine of your browser.

**Comment by ktabata** [comment]
Ok, sound works. Please remove browser cache and reload page if sound is not enabled. I tested on Chrome, Safari and Edge.
https://luxion.jp/em/html/

**Comment by ishani-rgb** [comment]
I think thats a fair compromise for sound, wow so Emscripten support is complete now isnt it?

**Comment by ktabata** [comment]
Some improvements.

* Fit canvas to window size
* Stop sound when invisible (and resume!)
* Keyboard UI
* Touch UI (for phone/tablet)

https://luxion.jp/em/html/  You need to reload or clear cache.

We need documents. Give me some time.

**Comment by ishani-rgb** [comment]
Im sorry, I didnt mean to rush you. The fact that this was done so quickly is great in itself. Since it seems to be in a very good state now, I think it might be okay to close this issue? What do you think?

**Comment by ktabata** [comment]
Ok, I pushed it to github. I think we can close this issue.

**Comment by ishani-rgb** [comment]
Cool
