### ISSUE TITLE
can this engine show Simplified. Chinese well?

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#26]
I am Chinese, I want to use Chinese in suika2 engine。
I changed default script and it can't show "测试" two characters
![image](https://user-images.githubusercontent.com/29478722/141482127-cdfd8edf-ca85-491c-987a-ba9936d1edeb.png)
If I use Chinese font,will it be resolved?

**Comment by ktabata** [comment]
Yes. I tested "测试" with XiaolaiSC-Regular.ttf font and the characters show.
You can use Chinese characters on Suika2.

**Comment by ktabata** [comment]
Here is the screenshot.
<img width="1202" alt="スクリーンショット 2021-11-13 13 20 30" src="https://user-images.githubusercontent.com/2771164/141605471-115bf2d6-33f6-46e0-8247-5e53f8bba15f.png">

The font I used is https://github.com/lxgw/kose-font

**Comment by 2439905184** [comment]
tanks,I tried alibaba's font,It can show Chinese well
