### ISSUE TITLE
I want to know how package.c pack png and ogg files into data01.arc

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#31]
Hi ktabata.Today I am learing from your code.
I want to know how package.c pack png and ogg file。
Does the codes from below link is to pack png and ogg files? But I didn't see any open source third party library like libpng and ogg lib in package.c.
https://github.com/ktabata/suika2/blob/bb527d9c7a9ce285c1a4f89a8dbf1e495136bcc0/tool/package.c#L215
So,package.c will just copy and paste binary from png or ogg files to data01.arc's file body?
I have no programming experience creating my own binary files。
I try to analyze your code. Here are the notes(in Chinese)
https://www.yuque.com/docs/share/b6c32a73-8c13-4341-a52d-350d70392740?# 《package.c-打包源码解析》
Here are about data01.arc's analyze
https://www.yuque.com/docs/share/e0d0fd5e-73af-41c4-9ba4-684bada708d3?# 《data.arc文件数据结构》
I used a hex editor to analyze data01.arc.
I think data01.arc is divided into three parts.
 1. file dir index(ascii)
2. file body(bin)
3. script code（txt）
![image](https://user-images.githubusercontent.com/29478722/142762955-ae3d57cd-66bf-48cf-ad17-c5b2b5f24f6e.png)
![image](https://user-images.githubusercontent.com/29478722/142762958-06ce0bf2-bdf4-48d9-b1d8-64f7c6576aa5.png)
I guess here is file body.
![image](https://user-images.githubusercontent.com/29478722/142762962-131d12e3-d6e6-4c59-b4ef-0e20511329e8.png)
and here is the third part,script
![image](https://user-images.githubusercontent.com/29478722/142762984-22f17ab2-4d8f-4931-9bc2-5053bf57f212.png)
I want to make a suika2-extracter,but I am a newer in this field.(Just to learn technology, not malicious cracking)

**Comment by ktabata** [comment]
Hi,
Yes, `package.c` just copies game files (png, ogg, txt) to data01.arc
file's body.
data01.arc has the index part (name and offset of the files) and body part.

Actually, I have `unpackage.c` to extract files for debug usage.
But game developers hate such a program, so I decided not to publish it.

If you want `unpackage.c`, I can personally give it to you.

2021年11月21日(日) 22:07 小沙盒工作室-社长 ***@***.***>:

**Comment by 2439905184** [comment]
thanks,I may want to make my own engine in c with ncine engine.
I also want to make my own bin game resource file.I am intereested in this.
I played tohou projecct and some other games.
Some of them have their own packaged resource file.
You can personally give me at email
2439905184@qq.com
or suchenglong018@126.com

**Comment by 2439905184** [comment]
By the way.Are there some game made with suika2 engine or some demos.
You can add a game showcase view on your offical website.
This is an advice

**Comment by ktabata** [comment]
There are some games but all of them are in Japanese.
The English demo was created recently with @sherlach 's cooperation.
I want additional demos but character illustration costs me a lot. (>$500)

**Comment by ishani-rgb** [comment]
Well for illustrations and etc.. There are many good things here (http://novelersmaterial.wosakana.com/)

Not sure about character portraits specifically though.
