### ISSUE TITLE
Does suika2 use libogg to decode ogg files?

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#32]
How suika2 play ogg files? It seems I can't find some code like "libogg" .On Windows,Just use direct sound to play ogg files?
I have no experience on asound and direct sound.
I want to try to use libogg to play ogg files in C console program。I compiled ogg at here https://github.com/2439905184/libogg-dist/releases.
I want to make a binary file, first part is ascii text, second part is ogg file's binary(I don't change ogg file's binary data,just copy from ogg to my won file.)

**Comment by ktabata** [comment]
Suika2 uses libogg and libvorbis via "vorbisfile" API which is included in libvorbis.
Please see https://github.com/ktabata/suika2/blob/master/src/wave.c
wave.c decodes .ogg file to wave data. Then dsound.c plays it.

If you want to play .ogg file in your own package file, use ov_callbacks and do your customized file read to "binary" part.
