### ISSUE TITLE
Failed to build in android studio

### ISSUE THREAD

**Issue by Cvar1984** [ktabata/suika2#35]
i run ./prepare-libs.sh to decompress libraries then Open Suika2 project (build/android) and wait till everything finish and then i build the project. but i got `C/C++: ../../../../src/main/cpp/main.c:268: error: undefined reference to 'video_command'`

![image](https://user-images.githubusercontent.com/32727560/168065563-6daacca6-d8c6-4d58-942f-7db9238b19bb.png)

**Comment by ktabata** [comment]
Hi! Thank you for reporting problem.

* Symbolic link to `cmd_video.c` in `build/android/app/src/main/cpp/` is missing
* Function `play_video()` in `src/ndkmain.c` is missing

I'll fix the problems shortly.

**Comment by ktabata** [comment]
@Cvar1984 Fixed! If you have problems, please let me know.
