### ISSUE TITLE
about game in 1920x1080 px support.

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#37]
I tried use this resolution。But suika2 reported me a wrong, then the engine shut down.
I meet this problem in older version of suika2.
I am sorry, because I don't give the wrong picture.
Later maybe upload it.
I just changed the config file with suika2's demo.
So I think there is may be a Maths problem.
Suika2 will do some behind Maths caculate (px caculate) when window init ang game init.

**Comment by 2439905184** [comment]
I remember I cleaned up the code.
Just leave a simple code
```
@bg xxx.png
```
This image is in 1920x1080 px

**Comment by ktabata** [comment]
Well, if the real display size is smaller than game display size, Suika2 shuts down with an error.
I tried 1920x1080 game on 1920x1080 display, but no error happened.

**Comment by 2439905184** [comment]
thanks

**Comment by ktabata** [comment]
It's a spec of Windows. We can't open a window which is larger than screen size.

**Comment by 2439905184** [comment]
> It's a spec of Windows. We can't open a window which is larger than screen size.

I use windows.
