### ISSUE TITLE
suika2.exe can be run on linux.

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#42]
This is very good.I didn't need to change any wine config file.
here is the screen picture.
This is a game.
![截图_suika exe_20220622194616](https://user-images.githubusercontent.com/29478722/175021627-2d1c53e8-886a-4c99-93cb-ccad58ad8195.png)
2a94c.png)
### detail 
![截图_选择区域_20220622194521](https://user-images.githubusercontent.com/29478722/175021426-49e01212-2cb0-4b50-a7b5-8f6c9048fe78.png)
![截图_选择区域_20220622194549](https://user-images.githubusercontent.com/29478722/175021916-45dddbb1-0a99-46b5-b02b-abef53292070.png)
### wine version:
wine-4.0 (Debian 4.0-2)

@ktabata I think you can add this point to offical website.

**Comment by ktabata** [comment]
Surprised? Suika2 was initially developed with Wine on Linux ;-)
We only use very old Windows APIs, and Wine implements them well.
Sometimes I want to use new APIs, but I avoid them for compatibility with older Windows and yes, Wine!
