### ISSUE TITLE
Does suika for linux is static link?

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#48]
![image](https://user-images.githubusercontent.com/29478722/178091069-8c6cecf0-d4e0-49ec-8ec4-93a23194885b.png)
When I copy suika to windows's file system and try to run it.I get this problem.
I removed this sav file and re-start suika2 ,this error showed again.
But when I use ./suika in linux system . It works well.

**Comment by 2439905184** [comment]
![image](https://user-images.githubusercontent.com/29478722/178091109-15b13344-dd09-498c-a141-9eae2d14b74d.png)

**Comment by ktabata** [comment]
It is not related to the sav files, but the config file.
Because sava/load screen is modified at 2.9.8,
you have to copy the following files from the newest ZIP to the game folder:

    * conf/config.txt
    * bg/load-bg.png
    * cg/save-bg.png
    * cg/save-fg.png
    * cg/load-bg.png
    * cg/load-fg.png

Sorry for inconvenience!
