### ISSUE TITLE
Add support to other image formats

### ISSUE THREAD

**Issue by maxchen32** [ktabata/suika2#53]
I advise to add support to jpeg image and maybe other common formats like bmp, gif, webp, etc.  
Though I've heard there're some problems in red parts of jpeg image, it still has the advantage of small file size and it's widely used. It seems that it will take quite a long time for jpeg to be replaced by other formats. Using jpeg as background image will be nice.

**Comment by ktabata** [comment]
Thank you for the suggestion.
When I made the first version of Suika2, I did't want to see ugly red component, so I didn't support JPEG.
That time we didn't have Web browser support, but for now, we support it, so the size of game impacts user experience a lot.
In the 2.9.x series, we'are currently working on a large enhancement of user interface, and there's not enough time to implement JPEG support in the next version.
So, could you wait for a while?
I'm sure I'll implement it, but it's not as soon as possible.
Suika2 lacks many features, and we're developing for them step by step.
I appreciate your understanding.

**Comment by ktabata** [comment]
I took the time to implement JPEG loading.
It will be reflected in the next version.
Thank you @maxchen32 for your suggestion!
